# Generated by Django 2.0 on 2018-01-27 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('father_name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('degree_of_education', models.CharField(choices=[('BSC', 'لیسانس'), ('MSC', 'فوق لیسانس'), ('PHD', 'دکترا')], default=None, max_length=3)),
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('national_number', models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRequest',
            fields=[
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('father_name', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('degree_of_education', models.CharField(choices=[('BSC', 'لیسانس'), ('MSC', 'فوق لیسانس'), ('PHD', 'دکترا')], default=None, max_length=3)),
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('national_number', models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('max_choice', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('register_start', models.DateTimeField(null=True)),
                ('register_end', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Candidate')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Election')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.ElectionType'),
        ),
        migrations.AddField(
            model_name='candidaterequest',
            name='election',
            field=models.ForeignKey(default=None, limit_choices_to={'allow_register': True}, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=None, limit_choices_to={'allow_register': True}, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Election'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='candidaterequest',
            unique_together={('id', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('id', 'election')},
        ),
    ]
