# Generated by Django 2.0 on 2018-01-27 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import e_voting_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=None, limit_choices_to=e_voting_system.models.limit_to, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='national_number',
            field=models.CharField(default='', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='candidaterequest',
            name='election',
            field=models.ForeignKey(default=None, limit_choices_to=e_voting_system.models.limit_to, on_delete=django.db.models.deletion.CASCADE, to='e_voting_system.Election'),
        ),
    ]
