# Generated by Django 2.0 on 2018-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_system', '0002_auto_20180127_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterequest',
            name='can_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='candidaterequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
