# Generated by Django 2.0 on 2018-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_system', '0003_auto_20180128_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterequest',
            name='can_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
