# Generated by Django 2.0 on 2018-01-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_system', '0004_auto_20180128_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='can_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidaterequest',
            name='can_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='candidaterequest',
            unique_together={('can_id', 'election')},
        ),
    ]
